// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitejournal

import (
	"database/sql"
)

type TradeReview struct {
	ID                       string         `json:"id"`
	CreatedAt                string         `json:"created_at"`
	AsOf                     string         `json:"as_of"`
	StrategyID               string         `json:"strategy_id"`
	StrategyConfigText       string         `json:"strategy_config_text"`
	PortfolioScope           sql.NullString `json:"portfolio_scope"`
	UniverseTickersJson      string         `json:"universe_tickers_json"`
	UserRequestedTickersJson sql.NullString `json:"user_requested_tickers_json"`
	ExecutionResult          string         `json:"execution_result"`
	AgentHarness             sql.NullString `json:"agent_harness"`
	AgentModel               sql.NullString `json:"agent_model"`
	AgentSkill               sql.NullString `json:"agent_skill"`
	UserPromptText           sql.NullString `json:"user_prompt_text"`
	ChatHistoryText          sql.NullString `json:"chat_history_text"`
	AgentSummary             sql.NullString `json:"agent_summary"`
	FinalDecision            sql.NullString `json:"final_decision"`
	HumanReasoningText       sql.NullString `json:"human_reasoning_text"`
	FinalValidationValid     sql.NullInt64  `json:"final_validation_valid"`
	FinalValidationSummary   sql.NullString `json:"final_validation_summary"`
	ReportPath               sql.NullString `json:"report_path"`
	WarningsText             sql.NullString `json:"warnings_text"`
}

type TradeReviewPosition struct {
	ID                  string          `json:"id"`
	TradeReviewID       string          `json:"trade_review_id"`
	Ticker              string          `json:"ticker"`
	ModelBucket         sql.NullString  `json:"model_bucket"`
	ModelIntent         sql.NullString  `json:"model_intent"`
	ModelScore          sql.NullFloat64 `json:"model_score"`
	ModelWeight         sql.NullFloat64 `json:"model_weight"`
	ModelDeltaWeight    sql.NullFloat64 `json:"model_delta_weight"`
	ModelEstimatedValue sql.NullFloat64 `json:"model_estimated_value"`
	ModelSharePrice     sql.NullFloat64 `json:"model_share_price"`
	ModelReason         sql.NullString  `json:"model_reason"`
	SizingMethod        sql.NullString  `json:"sizing_method"`
	RawKelly            sql.NullFloat64 `json:"raw_kelly"`
	FractionalKelly     sql.NullFloat64 `json:"fractional_kelly"`
	KellyTargetWeight   sql.NullFloat64 `json:"kelly_target_weight"`
	FinalTargetWeight   sql.NullFloat64 `json:"final_target_weight"`
	BindingConstraint   sql.NullString  `json:"binding_constraint"`
	CalibrationStatus   sql.NullString  `json:"calibration_status"`
	AgentDecision       sql.NullString  `json:"agent_decision"`
	AgentWeight         sql.NullFloat64 `json:"agent_weight"`
	AgentReason         sql.NullString  `json:"agent_reason"`
	HumanDecision       sql.NullString  `json:"human_decision"`
	HumanWeight         sql.NullFloat64 `json:"human_weight"`
	ExecutionPrice      sql.NullFloat64 `json:"execution_price"`
	ExecutionDate       sql.NullString  `json:"execution_date"`
	HumanReason         sql.NullString  `json:"human_reason"`
}
