// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlitejournal

import (
	"context"
	"database/sql"
)

const createTradeReview = `-- name: CreateTradeReview :exec
INSERT INTO trade_reviews (
  id,
  as_of,
  strategy_id,
  strategy_config_text,
  portfolio_scope,
  universe_tickers_json,
  user_requested_tickers_json,
  execution_result,
  agent_harness,
  agent_model,
  agent_skill,
  user_prompt_text,
  chat_history_text,
  agent_summary,
  final_decision,
  human_reasoning_text,
  final_validation_valid,
  final_validation_summary,
  report_path,
  warnings_text
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateTradeReviewParams struct {
	ID                       string         `json:"id"`
	AsOf                     string         `json:"as_of"`
	StrategyID               string         `json:"strategy_id"`
	StrategyConfigText       string         `json:"strategy_config_text"`
	PortfolioScope           sql.NullString `json:"portfolio_scope"`
	UniverseTickersJson      string         `json:"universe_tickers_json"`
	UserRequestedTickersJson sql.NullString `json:"user_requested_tickers_json"`
	ExecutionResult          string         `json:"execution_result"`
	AgentHarness             sql.NullString `json:"agent_harness"`
	AgentModel               sql.NullString `json:"agent_model"`
	AgentSkill               sql.NullString `json:"agent_skill"`
	UserPromptText           sql.NullString `json:"user_prompt_text"`
	ChatHistoryText          sql.NullString `json:"chat_history_text"`
	AgentSummary             sql.NullString `json:"agent_summary"`
	FinalDecision            sql.NullString `json:"final_decision"`
	HumanReasoningText       sql.NullString `json:"human_reasoning_text"`
	FinalValidationValid     sql.NullInt64  `json:"final_validation_valid"`
	FinalValidationSummary   sql.NullString `json:"final_validation_summary"`
	ReportPath               sql.NullString `json:"report_path"`
	WarningsText             sql.NullString `json:"warnings_text"`
}

func (q *Queries) CreateTradeReview(ctx context.Context, arg CreateTradeReviewParams) error {
	_, err := q.db.ExecContext(ctx, createTradeReview,
		arg.ID,
		arg.AsOf,
		arg.StrategyID,
		arg.StrategyConfigText,
		arg.PortfolioScope,
		arg.UniverseTickersJson,
		arg.UserRequestedTickersJson,
		arg.ExecutionResult,
		arg.AgentHarness,
		arg.AgentModel,
		arg.AgentSkill,
		arg.UserPromptText,
		arg.ChatHistoryText,
		arg.AgentSummary,
		arg.FinalDecision,
		arg.HumanReasoningText,
		arg.FinalValidationValid,
		arg.FinalValidationSummary,
		arg.ReportPath,
		arg.WarningsText,
	)
	return err
}

const createTradeReviewPosition = `-- name: CreateTradeReviewPosition :exec
INSERT INTO trade_review_positions (
  id,
  trade_review_id,
  ticker,
  model_bucket,
  model_intent,
  model_score,
  model_weight,
  model_delta_weight,
  model_estimated_value,
  model_share_price,
  model_reason,
  sizing_method,
  raw_kelly,
  fractional_kelly,
  kelly_target_weight,
  final_target_weight,
  binding_constraint,
  calibration_status,
  agent_decision,
  agent_weight,
  agent_reason,
  human_decision,
  human_weight,
  execution_price,
  execution_date,
  human_reason
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateTradeReviewPositionParams struct {
	ID                  string          `json:"id"`
	TradeReviewID       string          `json:"trade_review_id"`
	Ticker              string          `json:"ticker"`
	ModelBucket         sql.NullString  `json:"model_bucket"`
	ModelIntent         sql.NullString  `json:"model_intent"`
	ModelScore          sql.NullFloat64 `json:"model_score"`
	ModelWeight         sql.NullFloat64 `json:"model_weight"`
	ModelDeltaWeight    sql.NullFloat64 `json:"model_delta_weight"`
	ModelEstimatedValue sql.NullFloat64 `json:"model_estimated_value"`
	ModelSharePrice     sql.NullFloat64 `json:"model_share_price"`
	ModelReason         sql.NullString  `json:"model_reason"`
	SizingMethod        sql.NullString  `json:"sizing_method"`
	RawKelly            sql.NullFloat64 `json:"raw_kelly"`
	FractionalKelly     sql.NullFloat64 `json:"fractional_kelly"`
	KellyTargetWeight   sql.NullFloat64 `json:"kelly_target_weight"`
	FinalTargetWeight   sql.NullFloat64 `json:"final_target_weight"`
	BindingConstraint   sql.NullString  `json:"binding_constraint"`
	CalibrationStatus   sql.NullString  `json:"calibration_status"`
	AgentDecision       sql.NullString  `json:"agent_decision"`
	AgentWeight         sql.NullFloat64 `json:"agent_weight"`
	AgentReason         sql.NullString  `json:"agent_reason"`
	HumanDecision       sql.NullString  `json:"human_decision"`
	HumanWeight         sql.NullFloat64 `json:"human_weight"`
	ExecutionPrice      sql.NullFloat64 `json:"execution_price"`
	ExecutionDate       sql.NullString  `json:"execution_date"`
	HumanReason         sql.NullString  `json:"human_reason"`
}

func (q *Queries) CreateTradeReviewPosition(ctx context.Context, arg CreateTradeReviewPositionParams) error {
	_, err := q.db.ExecContext(ctx, createTradeReviewPosition,
		arg.ID,
		arg.TradeReviewID,
		arg.Ticker,
		arg.ModelBucket,
		arg.ModelIntent,
		arg.ModelScore,
		arg.ModelWeight,
		arg.ModelDeltaWeight,
		arg.ModelEstimatedValue,
		arg.ModelSharePrice,
		arg.ModelReason,
		arg.SizingMethod,
		arg.RawKelly,
		arg.FractionalKelly,
		arg.KellyTargetWeight,
		arg.FinalTargetWeight,
		arg.BindingConstraint,
		arg.CalibrationStatus,
		arg.AgentDecision,
		arg.AgentWeight,
		arg.AgentReason,
		arg.HumanDecision,
		arg.HumanWeight,
		arg.ExecutionPrice,
		arg.ExecutionDate,
		arg.HumanReason,
	)
	return err
}

const deleteTradeReview = `-- name: DeleteTradeReview :exec
DELETE FROM trade_reviews
WHERE id = ?
`

func (q *Queries) DeleteTradeReview(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTradeReview, id)
	return err
}

const finalizeTradeReview = `-- name: FinalizeTradeReview :exec
UPDATE trade_reviews
SET
  final_decision = ?,
  human_reasoning_text = ?,
  final_validation_valid = ?,
  final_validation_summary = ?,
  report_path = ?,
  warnings_text = ?
WHERE id = ?
`

type FinalizeTradeReviewParams struct {
	FinalDecision          sql.NullString `json:"final_decision"`
	HumanReasoningText     sql.NullString `json:"human_reasoning_text"`
	FinalValidationValid   sql.NullInt64  `json:"final_validation_valid"`
	FinalValidationSummary sql.NullString `json:"final_validation_summary"`
	ReportPath             sql.NullString `json:"report_path"`
	WarningsText           sql.NullString `json:"warnings_text"`
	ID                     string         `json:"id"`
}

func (q *Queries) FinalizeTradeReview(ctx context.Context, arg FinalizeTradeReviewParams) error {
	_, err := q.db.ExecContext(ctx, finalizeTradeReview,
		arg.FinalDecision,
		arg.HumanReasoningText,
		arg.FinalValidationValid,
		arg.FinalValidationSummary,
		arg.ReportPath,
		arg.WarningsText,
		arg.ID,
	)
	return err
}

const getTradeReview = `-- name: GetTradeReview :one
SELECT id, created_at, as_of, strategy_id, strategy_config_text, portfolio_scope, universe_tickers_json, user_requested_tickers_json, execution_result, agent_harness, agent_model, agent_skill, user_prompt_text, chat_history_text, agent_summary, final_decision, human_reasoning_text, final_validation_valid, final_validation_summary, report_path, warnings_text
FROM trade_reviews
WHERE id = ?
`

func (q *Queries) GetTradeReview(ctx context.Context, id string) (TradeReview, error) {
	row := q.db.QueryRowContext(ctx, getTradeReview, id)
	var i TradeReview
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AsOf,
		&i.StrategyID,
		&i.StrategyConfigText,
		&i.PortfolioScope,
		&i.UniverseTickersJson,
		&i.UserRequestedTickersJson,
		&i.ExecutionResult,
		&i.AgentHarness,
		&i.AgentModel,
		&i.AgentSkill,
		&i.UserPromptText,
		&i.ChatHistoryText,
		&i.AgentSummary,
		&i.FinalDecision,
		&i.HumanReasoningText,
		&i.FinalValidationValid,
		&i.FinalValidationSummary,
		&i.ReportPath,
		&i.WarningsText,
	)
	return i, err
}

const listTradeReviewPositions = `-- name: ListTradeReviewPositions :many
SELECT id, trade_review_id, ticker, model_bucket, model_intent, model_score, model_weight, model_delta_weight, model_estimated_value, model_share_price, model_reason, sizing_method, raw_kelly, fractional_kelly, kelly_target_weight, final_target_weight, binding_constraint, calibration_status, agent_decision, agent_weight, agent_reason, human_decision, human_weight, execution_price, execution_date, human_reason
FROM trade_review_positions
WHERE trade_review_id = ?
ORDER BY ticker ASC
`

func (q *Queries) ListTradeReviewPositions(ctx context.Context, tradeReviewID string) ([]TradeReviewPosition, error) {
	rows, err := q.db.QueryContext(ctx, listTradeReviewPositions, tradeReviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeReviewPosition
	for rows.Next() {
		var i TradeReviewPosition
		if err := rows.Scan(
			&i.ID,
			&i.TradeReviewID,
			&i.Ticker,
			&i.ModelBucket,
			&i.ModelIntent,
			&i.ModelScore,
			&i.ModelWeight,
			&i.ModelDeltaWeight,
			&i.ModelEstimatedValue,
			&i.ModelSharePrice,
			&i.ModelReason,
			&i.SizingMethod,
			&i.RawKelly,
			&i.FractionalKelly,
			&i.KellyTargetWeight,
			&i.FinalTargetWeight,
			&i.BindingConstraint,
			&i.CalibrationStatus,
			&i.AgentDecision,
			&i.AgentWeight,
			&i.AgentReason,
			&i.HumanDecision,
			&i.HumanWeight,
			&i.ExecutionPrice,
			&i.ExecutionDate,
			&i.HumanReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeReviewPositionsByTicker = `-- name: ListTradeReviewPositionsByTicker :many
SELECT p.id, p.trade_review_id, p.ticker, p.model_bucket, p.model_intent, p.model_score, p.model_weight, p.model_delta_weight, p.model_estimated_value, p.model_share_price, p.model_reason, p.sizing_method, p.raw_kelly, p.fractional_kelly, p.kelly_target_weight, p.final_target_weight, p.binding_constraint, p.calibration_status, p.agent_decision, p.agent_weight, p.agent_reason, p.human_decision, p.human_weight, p.execution_price, p.execution_date, p.human_reason
FROM trade_review_positions p
JOIN trade_reviews r ON r.id = p.trade_review_id
WHERE p.ticker = ?
ORDER BY r.as_of DESC, r.created_at DESC
`

func (q *Queries) ListTradeReviewPositionsByTicker(ctx context.Context, ticker string) ([]TradeReviewPosition, error) {
	rows, err := q.db.QueryContext(ctx, listTradeReviewPositionsByTicker, ticker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeReviewPosition
	for rows.Next() {
		var i TradeReviewPosition
		if err := rows.Scan(
			&i.ID,
			&i.TradeReviewID,
			&i.Ticker,
			&i.ModelBucket,
			&i.ModelIntent,
			&i.ModelScore,
			&i.ModelWeight,
			&i.ModelDeltaWeight,
			&i.ModelEstimatedValue,
			&i.ModelSharePrice,
			&i.ModelReason,
			&i.SizingMethod,
			&i.RawKelly,
			&i.FractionalKelly,
			&i.KellyTargetWeight,
			&i.FinalTargetWeight,
			&i.BindingConstraint,
			&i.CalibrationStatus,
			&i.AgentDecision,
			&i.AgentWeight,
			&i.AgentReason,
			&i.HumanDecision,
			&i.HumanWeight,
			&i.ExecutionPrice,
			&i.ExecutionDate,
			&i.HumanReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeReviews = `-- name: ListTradeReviews :many
SELECT id, created_at, as_of, strategy_id, strategy_config_text, portfolio_scope, universe_tickers_json, user_requested_tickers_json, execution_result, agent_harness, agent_model, agent_skill, user_prompt_text, chat_history_text, agent_summary, final_decision, human_reasoning_text, final_validation_valid, final_validation_summary, report_path, warnings_text
FROM trade_reviews
ORDER BY as_of DESC, created_at DESC
LIMIT ?
`

func (q *Queries) ListTradeReviews(ctx context.Context, limit int64) ([]TradeReview, error) {
	rows, err := q.db.QueryContext(ctx, listTradeReviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeReview
	for rows.Next() {
		var i TradeReview
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.AsOf,
			&i.StrategyID,
			&i.StrategyConfigText,
			&i.PortfolioScope,
			&i.UniverseTickersJson,
			&i.UserRequestedTickersJson,
			&i.ExecutionResult,
			&i.AgentHarness,
			&i.AgentModel,
			&i.AgentSkill,
			&i.UserPromptText,
			&i.ChatHistoryText,
			&i.AgentSummary,
			&i.FinalDecision,
			&i.HumanReasoningText,
			&i.FinalValidationValid,
			&i.FinalValidationSummary,
			&i.ReportPath,
			&i.WarningsText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTradeReviewReportPath = `-- name: SetTradeReviewReportPath :exec
UPDATE trade_reviews
SET report_path = ?
WHERE id = ?
`

type SetTradeReviewReportPathParams struct {
	ReportPath sql.NullString `json:"report_path"`
	ID         string         `json:"id"`
}

func (q *Queries) SetTradeReviewReportPath(ctx context.Context, arg SetTradeReviewReportPathParams) error {
	_, err := q.db.ExecContext(ctx, setTradeReviewReportPath, arg.ReportPath, arg.ID)
	return err
}

const upsertHumanTradeReviewPosition = `-- name: UpsertHumanTradeReviewPosition :exec
INSERT INTO trade_review_positions (
  id,
  trade_review_id,
  ticker,
  human_decision,
  human_weight,
  execution_price,
  execution_date,
  human_reason
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(trade_review_id, ticker) DO UPDATE SET
  human_decision = excluded.human_decision,
  human_weight = excluded.human_weight,
  execution_price = excluded.execution_price,
  execution_date = excluded.execution_date,
  human_reason = excluded.human_reason
`

type UpsertHumanTradeReviewPositionParams struct {
	ID             string          `json:"id"`
	TradeReviewID  string          `json:"trade_review_id"`
	Ticker         string          `json:"ticker"`
	HumanDecision  sql.NullString  `json:"human_decision"`
	HumanWeight    sql.NullFloat64 `json:"human_weight"`
	ExecutionPrice sql.NullFloat64 `json:"execution_price"`
	ExecutionDate  sql.NullString  `json:"execution_date"`
	HumanReason    sql.NullString  `json:"human_reason"`
}

func (q *Queries) UpsertHumanTradeReviewPosition(ctx context.Context, arg UpsertHumanTradeReviewPositionParams) error {
	_, err := q.db.ExecContext(ctx, upsertHumanTradeReviewPosition,
		arg.ID,
		arg.TradeReviewID,
		arg.Ticker,
		arg.HumanDecision,
		arg.HumanWeight,
		arg.ExecutionPrice,
		arg.ExecutionDate,
		arg.HumanReason,
	)
	return err
}
