// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitejournal

import (
	"context"
)

type Querier interface {
	CreateTradeReview(ctx context.Context, arg CreateTradeReviewParams) error
	CreateTradeReviewPosition(ctx context.Context, arg CreateTradeReviewPositionParams) error
	DeleteTradeReview(ctx context.Context, id string) error
	FinalizeTradeReview(ctx context.Context, arg FinalizeTradeReviewParams) error
	GetTradeReview(ctx context.Context, id string) (TradeReview, error)
	ListTradeReviewPositions(ctx context.Context, tradeReviewID string) ([]TradeReviewPosition, error)
	ListTradeReviewPositionsByTicker(ctx context.Context, ticker string) ([]TradeReviewPosition, error)
	ListTradeReviews(ctx context.Context, limit int64) ([]TradeReview, error)
	SetTradeReviewReportPath(ctx context.Context, arg SetTradeReviewReportPathParams) error
	UpsertHumanTradeReviewPosition(ctx context.Context, arg UpsertHumanTradeReviewPositionParams) error
}

var _ Querier = (*Queries)(nil)
